// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdCGN4lXO-rBEqpNqOTodkLuiEkyy4yn4',
    appId: '1:557557877145:web:5ab6b6cefcbcef1df12b08',
    messagingSenderId: '557557877145',
    projectId: 'notumcepte-3bde9',
    authDomain: 'notumcepte-3bde9.firebaseapp.com',
    storageBucket: 'notumcepte-3bde9.firebasestorage.app',
    measurementId: 'G-1VNP1YDT8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeSxOn-pMISFKwyXTNjq20F5jo3oI8F2A',
    appId: '1:557557877145:android:06151ebb9ed0097af12b08',
    messagingSenderId: '557557877145',
    projectId: 'notumcepte-3bde9',
    storageBucket: 'notumcepte-3bde9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuRosNQ-P5sWRbZkJ1NXZOOa-IiZG3Q38',
    appId: '1:557557877145:ios:7413fe56aad4006df12b08',
    messagingSenderId: '557557877145',
    projectId: 'notumcepte-3bde9',
    storageBucket: 'notumcepte-3bde9.firebasestorage.app',
    iosClientId: '557557877145-kt07ehcnmqdnnle2lo5q4g5t25hbna9r.apps.googleusercontent.com',
    iosBundleId: 'com.notumcepte.notumcepte',
  );

}